# -*- coding: utf-8 -*-
"""
Created on Wed Jul  1 17:36:38 2026

@author: jrich
"""

from archibald.geometry.airfoil.airfoil_families import get_kulfan_parameters
from archibald.geometry.airfoil.airfoil import Airfoil
from archibald.geometry.airfoil.kulfan_airfoil import KulfanAirfoil
import archibald.numpy as np

from typing import Sequence


def tall(array) -> np.ndarray:
    """Reshapes `array` into a column vector (n x 1)."""
    return np.reshape(array, (-1, 1))


def _wide(array) -> np.ndarray:
    """Reshapes `array` into a row vector (1 x n)."""
    return np.reshape(array, (1, -1))


def _leading_edge_camber(xc, mc) -> np.ndarray:
    """
    Computes the slope of the camber line at the leading edge (x=0), for a camber line defined by `_camberline`.

    Args:
        xc: Nondimensional chordwise location of maximum camber. Can be a scalar or an array (one value per
            camber line, if generating several at once).
        mc: Camber magnitude. Same shape convention as `xc`.

    Returns: The leading-edge camber slope (dy/dx at x=0), as a column vector.
    """
    return tall(-((xc**3 - 4 * xc + 2) * mc) / ((xc - 1) ** 3 * xc))


def _camberline(x, xc, mc) -> np.ndarray:
    """
    Computes a quartic camber line, parameterized by the nondimensional location of maximum camber (`xc`) and
    the camber magnitude (`mc`). Satisfies zero camber at the leading and trailing edges, with maximum camber
    `mc` located at `x = xc`.

    Args:
        x: Nondimensional chordwise coordinates at which to evaluate the camber line. A 1D array.
        xc: Nondimensional chordwise location of maximum camber. Can be a scalar or an array (one value per
            camber line, if generating several at once).
        mc: Camber magnitude. Same shape convention as `xc`.

    Returns: The camber height at each point in `x`, for each `(xc, mc)` pair. If `xc`/`mc` are scalars, returns
        a `1 x len(x)` array (a single camber line); if arrays of length `k`, returns a `k x len(x)` array.
    """
    denom = (xc - 1) ** 3 * xc**2

    A = tall(((xc**2 - 3 * xc + 1) * mc) / denom)
    B = tall(((-2 * xc**3 + 3 * xc**2 + 4 * xc - 2) * mc) / denom)
    C = tall(((xc**4 + 2 * xc**3 - 8 * xc**2 + xc + 1) * mc) / denom)
    D = _leading_edge_camber(xc, mc)

    x = _wide(x)

    return A @ x**4 + B @ x**3 + C @ x**2 + D @ x


class ThinAirfoil(KulfanAirfoil):
    """
    Definition for a thin-airfoil-theory-generated airfoil.

    Anatomy of a ThinAirfoil:

        A ThinAirfoil is generated by blending a parametric camber line (see `_camberline`, defined by its
        location of maximum camber `xc` and camber magnitude `mc`) onto the half-thickness distribution of a
        specified base airfoil. The resulting coordinates are then fit to a Kulfan (CST) parameterization, so
        that a ThinAirfoil is-a KulfanAirfoil and can be used anywhere a KulfanAirfoil is expected (e.g., as the
        `airfoil` of a `WingXSec`).

    `xc` and `mc` may be supplied as optimization variables (e.g., from `archibald.optimization.Opti`), in which
    case the resulting camber line -- and therefore the fitted Kulfan weights -- will be differentiable with
    respect to them.
    """

    def __init__(
        self,
        xc: float = 0.40,
        mc: float = 0.1862,
        base_airfoil: str | Airfoil = "e376",
        n_points_per_side: int = 100,
        n_weights_per_side: int = 8,
        name: str | None = None,
    ):
        """
        Generates a new ThinAirfoil.

        Args:

            xc: Nondimensional chordwise location of maximum camber, in the range (0, 1).

            mc: Camber magnitude (maximum camber height, nondimensionalized by chord).

            base_airfoil: The airfoil whose thickness distribution should be used. Can be given either as a
                string (a name recognized by `Airfoil`, e.g., "e376", "naca0012"), or as an `Airfoil` instance
                directly.

            n_points_per_side: Number of points to use per airfoil side (top/bottom) when repaneling the base
                airfoil and building the camber line, prior to fitting Kulfan weights.

            n_weights_per_side: Number of Kulfan (CST) weights to fit per side, when converting the generated
                coordinates into Kulfan parameters.

            name: Name of the airfoil [optional].
        """
        self.xc = xc
        self.mc = mc
        self.base_airfoil_name = (
            base_airfoil if isinstance(base_airfoil, str) else base_airfoil.name
        )
        self.n_points_per_side = n_points_per_side

        coordinates = self._compute_coordinates(
            xc=xc,
            mc=mc,
            base_airfoil=base_airfoil,
            n_points_per_side=n_points_per_side,
        )

        kulfan_parameters = get_kulfan_parameters(
            coordinates,
            n_weights_per_side=n_weights_per_side,
            N1=0.5,
            N2=1.0,
            n_points_per_side=n_points_per_side,
            use_leading_edge_modification=True,
            method="least_squares",
        )

        super().__init__(name=name, **kulfan_parameters)

    def __repr__(self) -> str:
        return (
            f"ThinAirfoil '{self.name}' "
            f"(xc={self.xc}, mc={self.mc}, base: '{self.base_airfoil_name}')"
        )

    @staticmethod
    def _compute_coordinates(
        xc: float,
        mc: float,
        base_airfoil: str | Airfoil,
        n_points_per_side: int,
    ) -> np.ndarray:
        """
        Computes the (x, y) coordinates of a thin airfoil, by adding a camber line (see `_camberline`) to the
        half-thickness distribution of `base_airfoil`.

        Args:
            xc: Nondimensional chordwise location of maximum camber.
            mc: Camber magnitude.
            base_airfoil: The base airfoil (name or Airfoil instance) to source the thickness distribution from.
            n_points_per_side: Number of points to use per side.

        Returns: A `(2 * n_points_per_side - 1) x 2` array of (x, y) coordinates, traversing from the trailing
            edge along the top surface to the leading edge, then along the bottom surface back to the trailing
            edge (standard airfoil coordinate convention).
        """
        if isinstance(base_airfoil, str):
            base_airfoil = Airfoil(base_airfoil)

        x = np.concatenate(
            (
                np.cosspace(1.0, 0.0, n_points_per_side),
                np.cosspace(0.0, 1.0, n_points_per_side)[1:],
            )
        )

        camber = _camberline(x, xc, mc)[0, :]

        thickness = base_airfoil.repanel(n_points_per_side).local_thickness(x)
        half_thickness = np.copy(thickness)
        half_thickness[: n_points_per_side - 1] *= -1.0
        half_thickness /= 2.0

        y = camber + half_thickness

        return np.stack([x, y], axis=1)

    def leading_edge_camber_slope(self) -> float:
        """
        Returns the slope of this airfoil's camber line at the leading edge (i.e., dy/dx at x=0), in degrees.

        Returns: The leading-edge camber slope, in degrees.
        """
        return np.degrees(np.arctan(_leading_edge_camber(self.xc, self.mc)[0, 0]))

    @classmethod
    def family(
        cls,
        xc: Sequence[float] | np.ndarray,
        mc: Sequence[float] | np.ndarray,
        base_airfoil: str | Airfoil = "e376",
        n_points_per_side: int = 100,
        n_weights_per_side: int = 8,
    ) -> list["ThinAirfoil"]:
        """
        Generates a family of ThinAirfoils, one for each `(xc, mc)` pair.

        Equivalent to calling `ThinAirfoil(xc=xc_i, mc=mc_i, ...)` for each pair `(xc_i, mc_i)` in
        `zip(xc, mc)`.

        Args:
            xc: A sequence of nondimensional chordwise locations of maximum camber, one per airfoil in the
                family.
            mc: A sequence of camber magnitudes, one per airfoil in the family. Must be the same length as `xc`.
            base_airfoil: The base airfoil (name or Airfoil instance) to source the thickness distribution from.
            n_points_per_side: Number of points to use per side.
            n_weights_per_side: Number of Kulfan (CST) weights to fit per side.

        Returns: A list of `ThinAirfoil` instances, one per `(xc, mc)` pair.
        """
        xc = np.atleast_1d(np.array(xc, dtype=float))
        mc = np.atleast_1d(np.array(mc, dtype=float))

        if len(xc) != len(mc):
            raise ValueError("`xc` and `mc` must be the same length.")

        return [
            cls(
                xc=xc_i,
                mc=mc_i,
                base_airfoil=base_airfoil,
                n_points_per_side=n_points_per_side,
                n_weights_per_side=n_weights_per_side,
            )
            for xc_i, mc_i in zip(xc, mc)
        ]


if __name__ == "__main__":
    from archibald.optimization import Opti

    opti = Opti()

    xc, mc = 0.40, 0.1862
    n = 50

    af = ThinAirfoil(
        xc=xc,
        mc=mc,
        base_airfoil="e376",
        n_points_per_side=n,
        name="thin_e376",
    )

    alpha = 0.0
    Re = 1e6

    opti.minimize(np.sum((mc - 0.00) ** 2))

    sol = opti.solve(verbose=False)

    aero = sol(af.get_aero_from_neuralfoil(alpha, Re))

    sol(af).draw()

    print(aero["analysis_confidence"], aero["CL"], aero["CD"])
    print(af.leading_edge_camber_slope())